server:
  address: 127.0.0.1
  port: 8080

spring:
  main:
    allow-circular-references: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234

  redis:
    host: localhost
    port: 6379
    database: 0

  mvc:
    servlet:
      load-on-startup: 1

  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB

sms:
  sdkAppId: 1400848864
  signName: "土豆雷的公众号"
  templateId : 1903093
  secretId: AKIDwhEXdXDgz9XifOwGSSEnDQOAj5D9wgda
  secretKey: ysfGhw2RlvupcDi0a1GJBrMe1OgnjXCj

casbin:
  model-path: C:\Users\lenovo\Desktop\code\Java\demo\src\main\java\com\potato\config\authz_model.conf

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: im_